### ISSUE TITLE
Colliders in open zones

### ISSUE THREAD

**Issue by agamotto** [quxios/QMovement#1]
Somehow colliders are being created on open zones, please see below example. I even tried to change the inner closed tiles to open, but the end result is the same. This same issue actually happened with previous plugin QuasiMovement...

![prive](https://user-images.githubusercontent.com/758487/28264141-80f77442-6ae1-11e7-8dc8-3275b1379e58.png)

**Comment by quxios** [comment]
Sorry for late reply, I forgot about this and couldn't remember where this was (sorry!)

Well QMovement and Quasi Movement stack tile colliders, while default MV uses the top most collider. So the issue you're most likely having is that the invisible tile you are using is most likely set as impassable. So open the tilesheet editor and set the invisible/blank tiles to passable and go to your map and you can repaint those invisible tiles again to be safe. Assuming your floor is on A, check the invisible tiles on B and/or C

**Comment by agamotto** [comment]
Great advice, I managed to get it fixed! Thanks a lot!

And sorry for raising this as an issue...
